# DELETED

# It is the interface of the DT. it takes the simulation input parameters and the control parameters, hence it runs the DT simulation
# It gives back the data_list which represents the simulation results

def digital_twin_run (NrOfSimul, ConwipVal, df_step_def, df_tblstep, df_orderpos, df_proctime, destination_folder_tabs, simul_output_file_path1, simul_output_file_path2, plantsim_model_path):
    from WPNo_type import WPNo_Orders #those are just algorithms that are useful to take the informations from the MES
    from WPNo_type import running_orders #those are just algorithms that are useful to take the informations from the MES
    from WPNo_type import merging_tables #those are just algorithms that are useful to take the informations from the MES
    from Output_Delete import delete_file #it is just an algorithm that deletes the files that have been generated by the previous simulations
    import openpyxl

    # Crea un nuovo workbook
    workbook = openpyxl.Workbook()
    # Seleziona il foglio attivo
    sheet = workbook.active
    # Imposta il valore 5 nella cella A1
    sheet['A1'] = ConwipVal
    # Salva il dataframe in un nuovo file Excel
    nome_file_salvataggio = fr"{destination_folder_tabs}\ConwipValue.xlsx"
    workbook.save(nome_file_salvataggio)

    from Simulation_Trigger import plantsim_trigger # it is the running function
    from KPI_Extraction import Output
    from KPI_Extraction import sim_results
    data_list = []
    ii = 1
    while ii <= NrOfSimul:
        # Esecuzione degli script, partono quando il precedente finisce
        Order_Table = WPNo_Orders(df_step_def,df_proctime,df_orderpos,destination_folder_tabs)
        RunningOrders_Table = running_orders(df_tblstep,destination_folder_tabs)
        merging_tables(RunningOrders_Table,Order_Table,destination_folder_tabs)
        delete_file(simul_output_file_path1)
        delete_file(simul_output_file_path2)
        plantsim_trigger (plantsim_model_path,simul_output_file_path2)
        [media_throughput, media_cycle_time, tot_energy_consumption] = Output(simul_output_file_path1,simul_output_file_path2)
        data = sim_results(media_throughput,media_cycle_time,ii, tot_energy_consumption)
        data_list.append(data)
        print(data)
        ii += 1
    return(data_list)