# This algorithm deletes the files that have been generated by the previous simulations
import os

def delete_file(file_path):
    if os.path.exists(file_path):  # Verifica se il file esiste
        os.remove(file_path)  # Rimuove il file
        print(f"Il file {file_path} è stato eliminato con successo.")
    else:
        print(f"Il file {file_path} non esiste.")

# Esempio di utilizzo
#file_path = r"C:\Users\Fedemotta\Desktop\Linea Lab\Outputs & Extraction\FinishTimes.xlsx" # Inserisci il percorso completo del file da eliminare
#delete_file(file_path)
